db:
  name: aom
  address: devServer
  port: 3306
  type: mysql
  encoding: utf-8
  timezone: UTC
  driver: org.mariadb.jdbc.Driver
  username: root
  password: 123456
redis:
  address: devServer
  port: 6379
  password:
  database: 0
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:${db.type}://${db.address}:${db.port}/${db.name}
    username: ${db.username}
    password: ${db.password}
    driver-class-name: ${db.driver}
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      db-type: mysql
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 5000
      keep-alive: true
      filter:
        stat:
        enabled: true
        db-type: ${db.type}
        log-slow-sql: true
        slow-sql-millis: 2000
      web-stat-filter:
        enabled: true
        exclusions:
        - "*.js"
        - "*.gif"
        - "*.jpg"
        - "*.png"
        - "*.css"
        - "*.ico"
        - "/druid/*"
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: admin
        allow:
      remove-abandoned: false
      test-while-idle: true
  jpa:
    database: mysql
    database-platform: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
  redis:
    host: ${redis.address}
    port: ${redis.port}
    password: ${redis.password}
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    database: ${redis.database}
  output:
    ansi:
      enabled: always
  mvc:
    servlet:
      load-on-startup: 1
    converters:
      preferred-json-mapper: gson
server:
  port: 8080
logging:
  config: classpath:log4j2/log4j2-prod.xml
